# Generated by Django 5.0.2 on 2024-02-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Register',
        ),
    ]
